version: "3.8"

services:
  blitz_compilation:
    build:
      context: .
      args:
        - COMPILE_ALL=${COMPILE_ALL}
        - FOR_X=${FOR_X}
    privileged: true
    stdin_open: true
    volumes:
      - .:/host
    tty: true
    ports:
      - "6756:6756"
